### ISSUE TITLE
无服务器架构能用于100ms延迟以内的实时竞技游戏吗

### ISSUE THREAD

**Issue by SteveCruise** [aliyun/serverless-function-compute-examples#1]

**Comment by joyeecheung** [comment]
最好的方式是写 demo 尝试一下，如果效果好，可以提交 PR（暂时没有 CONTRIBUTING.md，稍后补上）。
The best way to figure this out is to write a demo and see if it works. You can submit a PR if your demo turns out working fine. (We don't have a CONTRIBUTING.md yet but it will be added later).

不适合在这个 repo 讨论，关闭。[云栖论坛](https://bbs.aliyun.com) 或者 [serverless 论坛](https://forum.serverless.com/) 更适合讨论这些问题。
Closing because this repo is not the right place to discuss such issues. I would recommend [Yunqi forum](https://bbs.aliyun.com) or the [serverless forum](https://forum.serverless.com/) for this.

**Comment by JacksonTian** [comment]
如果不需要长连接，fc是适合的。

**Comment by SteveCruise** [comment]
@JacksonTian 在哪见过你，实时游戏需要长连接或者udp，哎，可惜了。

**Comment by SteveCruise** [comment]
@joyeecheung 谢谢谢谢谢谢！
